# Generated by Django 5.2.17 on 2026-09-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_recommendation', models.TextField(blank=True, null=True)),
                ('priority_score', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
