# Generated by Django 5.2.17 on 2026-09-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_technology_organizationtechstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
