# Generated by Django 5.2.17 on 2026-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_technology_description_alter_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('os', 'Operating Systems'), ('web', 'Web Technologies'), ('database', 'Databases'), ('language', 'Programming Languages'), ('cloud', 'Cloud Platforms'), ('security', 'Security Tools')], default='os', max_length=20),
        ),
    ]
